### ISSUE TITLE
Stable Diffusion 2 and Apple Silicon/MPS

### ISSUE THREAD

**Issue by FahimF** [huggingface/diffusers#1398]
### Describe the bug

The diffusers code will run under Apple Silicon/MPS for Stable Diffusion 2.0 but the result is always noise. No images are generated.

Additionally, if you specify `pipe.enable_attention_slicing()`, then you get the following error — this is with the latest, dev source from the site and is not using the stable release.

```
│ /Users/fahim/Code/Python/sd2/diff.py:11 in <module>                                              │
│                                                                                                  │
│    8 device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.has_mps el    │
│    9 scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")         │
│   10 pipe = StableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler, safety_che    │
│ ❱ 11 pipe.enable_attention_slicing()                                                             │
│   12 # pipe = StableDiffusionPipeline.from_pretrained(model_id).to(device)                       │
│   13                                                                                             │
│   14 prompt = "a photo of an astronaut riding a tricerotops"                                     │
│                                                                                                  │
│ /Users/fahim/miniconda3/envs/ml/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion │
│ /pipeline_stable_diffusion.py:170 in enable_attention_slicing                                    │
│                                                                                                  │
│   167 │   │   if slice_size == "auto":                                                           │
│   168 │   │   │   # half the attention head size is usually a good trade-off between             │
│   169 │   │   │   # speed and memory                                                             │
│ ❱ 170 │   │   │   slice_size = self.unet.config.attention_head_dim // 2                          │
│   171 │   │   self.unet.set_attention_slice(slice_size)                                          │
│   172 │                                                                                          │
│   173 │   def disable_attention_slicing(self):                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: unsupported operand type(s) for //: 'list' and 'int'
```

### Reproduction

This is the script used:

```
import torch
from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler

model_id = "stabilityai/stable-diffusion-2"

# Use the Euler scheduler here instead
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.has_mps else "cpu")
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = StableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler, safety_checker=None).to(device)

prompt = "a photo of an astronaut riding a tricerotops"
image = pipe(prompt, height=512, width=512, num_inference_steps=25).images[0]

image.save("test.png")
```

### System Info

- `diffusers` version: 0.9.0.dev0
- Platform: macOS-13.0-arm64-arm-64bit
- Python version: 3.9.13
- PyTorch version (GPU?): 1.14.0.dev20221124 (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: yes. See script
- Using distributed or parallel set-up in script?: no. See script

**Comment by federicotorrielli** [comment]
The same error happens on collab, when calling `...StableDiffusionPipeline.from_pretrained(...`

**Comment by kashif** [comment]
Fixed by #1397

**Comment by pcuenca** [comment]
Both attention slicing and mps should now be fixed in `main`. Thanks againg to @Birch-san and @kashif for their work in #1410 and #1411!

**Comment by FahimF** [comment]
@pcuenca I couldn't get the solution by @Birch-san to give me a valid image at my end but I thought maybe I was doing something wrong. But I just updated the main branch on my machine and tried to generate an image using the same code above and I still don't get a valid image ... Here's the result I get ...
![test](https://user-images.githubusercontent.com/181110/203995361-011dcbe8-0eb5-44bf-8687-f98b12d97a44.png)

I don't know if perhaps I've missed something obvious or if there might still be an issue?

If there's anything I can do to test further, please let me know. (Not urgent at my end since I do have the StabilityAI code working fine on my machine ...) Just letting you know in case there's still an issue 🙂

**Comment by kashif** [comment]
I tried on a fresh install:

```py
import torch
from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler

model_id = "stabilityai/stable-diffusion-2"

# Use the Euler scheduler here instead
device = torch.device("cuda" if torch.cuda.is_available() else "mps" if torch.has_mps else "cpu")
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = StableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler, safety_checker=None).to(device)

prompt = "a photo of an astronaut riding a tricerotops"
image = pipe(prompt, height=512, width=512, num_inference_steps=25).images[0]
```

where:

```py
device

device(type='mps')
```

and get:

![astro](https://user-images.githubusercontent.com/8100/203996749-4023cf90-8c84-464c-adfd-d29208d72487.png)

**Comment by FahimF** [comment]
I'm not sure what might be wrong at my end then, but I've been doing stuff since 2:00am and so might be missing something basic 🙂 Will try again tomorrow and post here if it's still the same at my end since I'm not sure what to look for in order to figure out what is going wrong ...

**Comment by kashif** [comment]
Not a problem yes I feel you! BTW I am on:

```
torch.__version__

'1.14.0.dev20221124'
```

**Comment by FahimF** [comment]
I'm on that torch nightly version as well, so it's not that 🙂 And the StabilityAI version of the code works fine here. Just can't get diffusers to work but we'll leave it be for now. Not sure I can think straight any longer today 😃

**Comment by FahimF** [comment]
After testing today, I can confirm that this works on my Apple M1 🙂 Thank you!

**Comment by patrickvonplaten** [comment]
Cool!

**Comment by lkaupp** [comment]
any idea when this fix is also available in the inpainting repository?
