### ISSUE TITLE
OSError with stable-diffusion-v1-4 model 

### ISSUE THREAD

**Issue by liu00222** [huggingface/diffusers#2036]
### Describe the bug

When I load the stable diffusion v1-4 model, the following error occurs: 

```
python my_script.py 
2023-01-19 02:56:57.587154: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2023-01-19 02:56:57.587219: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Downloading: 100%|████████████████████████████████████| 582/582 [00:00<00:00, 321kB/s]
Downloading: 100%|████████████████████████████████████| 518/518 [00:00<00:00, 262kB/s]
Downloading: 100%|███████████████████████████████| 4.85k/4.85k [00:00<00:00, 2.28MB/s]
Downloading: 100%|█████████████████████████████████| 608M/608M [00:06<00:00, 93.4MB/s]
Downloading: 100%|███████████████████████████████| 1.22G/1.22G [00:12<00:00, 97.6MB/s]
Downloading: 100%|████████████████████████████████████| 209/209 [00:00<00:00, 134kB/s]
Downloading: 100%|████████████████████████████████████| 346/346 [00:00<00:00, 174kB/s]
Downloading: 100%|████████████████████████████████████| 617/617 [00:00<00:00, 327kB/s]
Downloading: 100%|█████████████████████████████████| 246M/246M [00:02<00:00, 96.7MB/s]
Downloading: 100%|█████████████████████████████████| 492M/492M [00:04<00:00, 99.5MB/s]
Downloading: 100%|█████████████████████████████████| 525k/525k [00:00<00:00, 10.5MB/s]
Downloading: 100%|████████████████████████████████████| 472/472 [00:00<00:00, 290kB/s]
Downloading: 100%|████████████████████████████████████| 808/808 [00:00<00:00, 459kB/s]
Downloading: 100%|███████████████████████████████| 1.06M/1.06M [00:00<00:00, 12.2MB/s]
Downloading: 100%|████████████████████████████████| 1.07k/1.07k [00:00<00:00, 789kB/s]
Downloading: 100%|███████████████████████████████| 1.72G/1.72G [00:17<00:00, 97.9MB/s]
Downloading: 100%|████████████████████████████████████| 601/601 [00:00<00:00, 430kB/s]
Downloading: 100%|█████████████████████████████████| 167M/167M [00:01<00:00, 84.1MB/s]
Fetching 18 files: 100%|██████████████████████████████| 18/18 [00:48<00:00,  2.70s/it]
Traceback (most recent call last):
  File "generate_raw_image.py", line 57, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16, safety_checker=None).to(device)
  File "/home/yl764/miniconda3/envs/diff/lib/python3.8/site-packages/diffusers/pipeline_utils.py", line 708, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/yl764/miniconda3/envs/diff/lib/python3.8/site-packages/diffusers/modeling_utils.py", line 452, in from_pretrained
    model_file = cls._get_model_file(
  File "/home/yl764/miniconda3/envs/diff/lib/python3.8/site-packages/diffusers/modeling_utils.py", line 593, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory /home/yl764/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/snapshots/04f177d998ae448d67ba0cdac27772ac292ea3c7/vae.
```

I manually checked the directory where the model is downloaded, i.e., '/home/yl764/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/' in my situation. There is no 'diffusion_pytorch_model.bin' file. 

### Reproduction

When I run the following code, the aforementioned error occurs: 

```
from diffusers import StableDiffusionPipeline
import torch

device = 'cuda:5'
model_path = f'CompVis/stable-diffusion-v1-4'
pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16).to(device)
```

I tried to change 'v1-4' to other versions of models, such as 'v1-3', and they all work. It seems like 'v1-4' is the only one that's missing the model file in the vae directory. 

### System Info

- `diffusers` version: 0.11.1
- Platform: Linux-4.15.0-189-generic-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by andreemic** [comment]
Yep... caused by the newest commit in [CompVis/stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4/commit/04f177d998ae448d67ba0cdac27772ac292ea3c7). It for some reason deletes the diffusion_pytorch_model.bin file and replaces it with safetensor.
<img width="373" alt="Screenshot 2023-01-19 at 08 51 57" src="https://user-images.githubusercontent.com/27695722/213385133-0b11b56c-7510-41f2-bfb8-11f8d6f55f5b.png">

@patrickvonplaten any resources or context on how to fix this? I'm guessing changing the model loading code in the [Imagic community pipeline](https://github.com/huggingface/diffusers/blob/main/examples/community/imagic_stable_diffusion.py)

**Comment by pcuenca** [comment]
Should be working now, could you please double-check? Our apologies for the trouble!

**Comment by patrickvonplaten** [comment]
Very sorry about this. We accidentally deleted PyTorch files when adding the safetensors checkpoints because of a bug here: https://github.com/huggingface/diffusers/pull/2038 . 

I should have been more vigilant when adding files to the repo - we have better safety mechanisms in place now.

**Comment by liu00222** [comment]
It works now. Thank you for your helps. I really appreciate your prompt responses.

**Comment by andreemic** [comment]
> Very sorry about this. We accidentally deleted PyTorch files when adding the safetensors checkpoints because of a bug here: #2038 .
> 
> I should have been more vigilant when adding files to the repo - we have better safety mechanisms in place now.

all good, appreciate the quick resolution!

**Comment by surya-narayanan** [comment]
i still face this issue- what should i do to fix it? upgrade / update?

**Comment by garvit-gupta** [comment]
Hi. I seem to be facing the same issue. Is there any specific version of the library that I should be using?
