### ISSUE TITLE
PyTorch 2.0 and ONNX converter 

### ISSUE THREAD

**Issue by ForserX** [huggingface/diffusers#2878]
```cmd
UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 14 is not supported.
```
More info: https://github.com/pytorch/pytorch/issues/97262

**Comment by justinchuby** [comment]
@abock

**Comment by BowenBao** [comment]
cc @titaiwangms using atenlib for ts exporter

**Comment by patrickvonplaten** [comment]
cc @anton-l and @echarlaix here as well

**Comment by justinchuby** [comment]
For reference https://github.com/pytorch/pytorch/issues/97262 is a transitional workaround until we expose the new dynamo interface

**Comment by ForserX** [comment]
Isn't it better to fix the converter script?

https://github.com/ForserX/StableDiffusionUI/commit/195e21f1491042262bb5e512d1d03e8fb4a7d56c

**Comment by fxmarty** [comment]
@justinchuby Out of curiosity, what do you mean by

> expose the new dynamo interface

?

**Comment by justinchuby** [comment]
We are working on a new torch.onnx.dynamo_export API which will use dynamo for graph capturing instead of torch.jit. https://github.com/pytorch/pytorch/pull/97920

**Comment by titaiwangms** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/99658

**Comment by ForserX** [comment]
It remains to wait for the release of PyTorch 2.1.0

**Comment by ashimatyuk** [comment]
Hi,
I'm facing "torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 14 is not supported" when using convert_stable_diffusion_checkpoint_to_onnx.py for converting sd-v1-5-inpainting.ckpt to onnx. As I can see it was fixed (as @titaiwangms mentioned above) but it still doesn't work. Am I doing smth wrong? The error is raised on the unet stage, text_encoder has been converted successfully.
