### ISSUE TITLE
Tiny Autoencoder + ControlNet Pipelines doesn't work

### ISSUE THREAD

**Issue by aaronsantiago** [huggingface/diffusers#5860]
### Describe the bug

It seems like the slight architectural differences between autoencoder_tiny and the regular autoencoderKL are preventing it from being used with ControlNet pipelines. I'm finding that if I make a slight modification to the ControlNet pipelines, everything works fine. The only thing preventing me from making a pull request is that I'm unsure of what side effects this could have for general use.

Simply, the pipelines need to read from the `decoder_block_out_channels` in the vae if it is the tiny autoencoder rather than `block_out_channels` here:
https://github.com/huggingface/diffusers/blob/4e54dfe985293df9e6e86828d7a2763d076879f5/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py#L174

and here:
https://github.com/huggingface/diffusers/blob/4e54dfe985293df9e6e86828d7a2763d076879f5/src/diffusers/pipelines/controlnet/pipeline_controlnet.py#L176

If this wouldn't break anything I could write code to detect if it is an AutoencoderTiny and read the proper field.

### Reproduction

This code includes the usage of LCM LoRA and functions properly when I make the change to the SDXL controlnet pipeline described above.

```import torch
from diffusers import (LCMScheduler, AutoPipelineForText2Image, StableDiffusionPipeline, StableDiffusionXLPipeline, EulerAncestralDiscreteScheduler)

import numpy as np
from PIL import Image

from transformers import DPTFeatureExtractor, DPTForDepthEstimation
from diffusers import ControlNetModel, StableDiffusionXLControlNetPipeline, AutoencoderTiny
from diffusers.utils import load_image
import os


depth_estimator = DPTForDepthEstimation.from_pretrained("Intel/dpt-hybrid-midas").to("cuda")
feature_extractor = DPTFeatureExtractor.from_pretrained("Intel/dpt-hybrid-midas")
controlnet = ControlNetModel.from_pretrained(
    "diffusers/controlnet-depth-sdxl-1.0",
    variant="fp16",
    use_safetensors=True,
    torch_dtype=torch.float16,
).to("cuda")
vae = AutoencoderTiny.from_pretrained("madebyollin/taesdxl", torch_dtype=torch.float16, use_safetensors=True).to("cuda")


def load_model():
    model = StableDiffusionXLControlNetPipeline.from_pretrained(
        "segmind/SSD-1B",
        controlnet=controlnet,
        vae=vae,
        variant="fp16",
        use_safetensors=True,
        torch_dtype=torch.float16,
    ).to("cuda")

    model.safety_checker = None
    model.to(torch.device('cuda'))

    model.scheduler = LCMScheduler.from_config(model.scheduler.config)
    adapter_id = "latent-consistency/lcm-lora-ssd-1b"
    # load and fuse lcm lora
    model.load_lora_weights(adapter_id)
    model.fuse_lora()
    return model


def get_depth_map(image):
    image = feature_extractor(images=image, return_tensors="pt").pixel_values.to("cuda")
    with torch.no_grad(), torch.autocast("cuda"):
        depth_map = depth_estimator(image).predicted_depth

    depth_map = torch.nn.functional.interpolate(
        depth_map.unsqueeze(1),
        size=(1024, 1024),
        mode="bicubic",
        align_corners=False,
    )
    depth_min = torch.amin(depth_map, dim=[1, 2, 3], keepdim=True)
    depth_max = torch.amax(depth_map, dim=[1, 2, 3], keepdim=True)
    depth_map = (depth_map - depth_min) / (depth_max - depth_min)
    image = torch.cat([depth_map] * 3, dim=1)

    image = image.permute(0, 2, 3, 1).cpu().numpy()[0]
    image = Image.fromarray((image * 255.0).clip(0, 255).astype(np.uint8))
    return image


model = load_model()

prompt = "stormtrooper lecture, photorealistic"
image = load_image("https://huggingface.co/lllyasviel/sd-controlnet-depth/resolve/main/images/stormtrooper.png")
controlnet_conditioning_scale = 0.5  # recommended for good generalization

depth_image = get_depth_map(image)

images = model(
    prompt,
    image=depth_image,
    num_inference_steps=3,
    height=512,
    width=512,
    guidance_scale=1.5,
    controlnet_conditioning_scale=controlnet_conditioning_scale,
).images
```

### System Info

- `diffusers` version: 0.23.1
- Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.9.16
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: RTX 3090
- Using distributed or parallel set-up in script?: no

### Who can help?

 @sayakpaul @yiyixuxu

**Comment by patrickvonplaten** [comment]
Hey @aaronsantiago,

Thanks a lot for the easy-to-reproduce bug. The PR #5880 should solve it! 

Could you maybe give it a try and see whether it solves your use case?

```
pip install git+https://github.com/huggingface/diffusers.git@make_vae_work_all
```

**Comment by andypotato** [comment]
I ran into the same issue as described by @aaronsantiago in his original report while using the `StableDiffusionXLControlNetImg2ImgPipeline` and `AutoencoderTiny`.

Using the tag `make_work_vae_all` as @patrickvonplaten suggests did not solve the issue for me. Also using the latest git branch does not make any difference.

It does work normally with the `StableDiffusionXLControlNetPipeline`, just once I try img2img the pipeline will just be stuck at zero iterations forever.

**Comment by sayakpaul** [comment]
Can you create a new issue and help us reproduce the problem with a fully reproducible code snippet?
