### ISSUE TITLE
AttributeError: 'Parameter' object has no attribute 'named_children'

### ISSUE THREAD

**Issue by klyuhang9** [huggingface/diffusers#858]
### Describe the bug

Hi, friends, I meet a problem  I hope to get your help.

When I run the code as follow:

`from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained("PATH_OF_MODEL/stable-diffusion",device_map="auto",torch_type=torch.float16, revision="fp16")
`
I save the  model in the path "PATH_OF_MODEL/stable-diffusion" from the https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main
Then, I get the error as follow:

`ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/diffusers/pipeline_utils.py", line 517, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2265, in from_pretrained
    device_map = infer_auto_device_map(
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 480, in infer_auto_device_map
    max_layer_size, max_layer_names = get_max_layer_size(modules_to_treat, module_sizes, no_split_module_classes)
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 261, in get_max_layer_size
    modules_children = list(module.named_children())
AttributeError: 'Parameter' object has no attribute 'named_children'
`
My environment: python=3.9.13, diffusers=0.5.1  torch=1.12.1, transformers = 4.12.1,  spacy = 3.4.1,accelerate=0.13.1  which run on  ubuntu=22.04.  

I don't know why, I sincerely to get your team help.Thanks,bro!

### Reproduction

`from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained("PATH_OF_MODEL/stable-diffusion",device_map="auto",torch_type=torch.float16, revision="fp16")'

### Logs

```shell
`ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/diffusers/pipeline_utils.py", line 517, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2265, in from_pretrained
    device_map = infer_auto_device_map(
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 480, in infer_auto_device_map
    max_layer_size, max_layer_names = get_max_layer_size(modules_to_treat, module_sizes, no_split_module_classes)
  File "/home/klyuhang9/miniconda3/envs/PY_TEST/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 261, in get_max_layer_size
    modules_children = list(module.named_children())
AttributeError: 'Parameter' object has no attribute 'named_children'
```

### System Info

My environment: python=3.9.13, diffusers=0.5.1  torch=1.12.1, transformers = 4.12.1,  spacy = 3.4.1,accelerate=0.13.1  which run on  ubuntu=22.04.

**Comment by patrickvonplaten** [comment]
Hey @klyuhang9,

Thanks a lot for the issue. This is a bug that we recently fixed in `accelerate` here: https://github.com/huggingface/accelerate/pull/747

I'm not exactly sure when a new `accelerate` version will come out - also cc @sgugger @muellerzr here (not sure if it's worth making a patch release for this)
Until then could you try the same command with the `"main"` version of `accelerate`:

```
pip install git+https://github.com/huggingface/accelerate.git
```

?

**Comment by sgugger** [comment]
I can put it in a patch later today!

**Comment by sgugger** [comment]
Patch is out on Pypi.

**Comment by patrickvonplaten** [comment]
Thanks a lot! @klyuhang9 doing:

```
pip install --upgrade accelerate
pip install --upgrade transformers
pip install --upgrade diffusers
```

should make your code above run correctly

**Comment by junshutang** [comment]
hi~ @patrickvonplaten I still have the same Error: AttributeError: 'StableDiffusionPipeline' object has no attribute 'named_children'. 
I have tried to update the version of accelerate/transformers/diffusers, and my environment: diffusers=0.7.2, torch=1.10.0+cu113, transformers = 4.24.0, accelerate=0.15.0.dev0.
Can you help me fix it out?
